### ISSUE TITLE
Unicode ZWNJ does not work

### ISSUE THREAD

**Issue by hosseinn** [proton/zNotes#36]
It is not possible to insert Unicode character ZWNJ in the text. This is the bug from the upstream Qt 5:
https://bugreports.qt.io/browse/QTBUG-42074

Any workarounds?

**Comment by ozky** [comment]
Qt need to first fix that problem then znotes can be updated to work with that unicode character you need to use. 
Also znotes seems to be quite slow maintaned project this point.

**Comment by hosseinn** [comment]
The Qt bug is now fixed, and ZWNJ is now ok in zNotes.
